# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-04 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='mobile',
        ),
    ]
