# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-05 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20171004_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='\u6563\u5217\u7801'),
        ),
    ]
