# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-15 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='comment_user',
        ),
    ]
