# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-15 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20171015_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='anonymous_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u533f\u540d'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
