# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-12 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LofterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('content', models.CharField(max_length=300, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('fav_click', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
            ],
            options={
                'verbose_name': '\u5185\u5bb9\u7ba1\u7406',
                'verbose_name_plural': '\u5185\u5bb9\u7ba1\u7406',
            },
        ),
    ]
