# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-12 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loftermodel',
            name='image',
            field=models.ImageField(default=2, upload_to='courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loftermodel',
            name='content',
            field=models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
