# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-12 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0002_auto_20170912_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loftermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
