# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-12 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0003_auto_20170912_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loftermodel',
            options={'verbose_name': '\u5185\u5bb9', 'verbose_name_plural': '\u5185\u5bb9'},
        ),
    ]
