# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-13 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0004_auto_20170912_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='loftermodel',
            name='fav_bool',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u70b9\u51fb\u8fc7'),
        ),
    ]
