# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-13 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0005_loftermodel_fav_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loftermodel',
            name='fav_bool',
        ),
    ]
