# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 12:47
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0006_remove_loftermodel_fav_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loftermodel',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
