# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 15:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0007_auto_20171014_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.LofterModel', verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u8bc4\u8bba',
                'verbose_name_plural': '\u6587\u7ae0\u8bc4\u8bba',
            },
        ),
    ]
