# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0008_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='essay',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
