# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-16 03:34
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0009_auto_20171014_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loftermodel',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='loftermodel',
            name='image',
            field=models.ImageField(blank=True, default='courses/2017/09/p1.jpg', null=True, upload_to='courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
