# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0010_auto_20171016_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='loftermodel',
            name='author_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u4f5c\u8005ID'),
        ),
    ]
