# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-18 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0011_loftermodel_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loftermodel',
            name='fav_click',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570'),
        ),
    ]
