# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0012_auto_20171018_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loftermodel',
            options={'verbose_name': '\u6587\u7ae0\u7ba1\u7406', 'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406'},
        ),
    ]
